# Generated by Django 3.1 on 2020-08-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200829_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilephoto',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
