# Generated by Django 3.1 on 2020-08-29 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200829_1308'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfilePhoto',
        ),
    ]
