# Generated by Django 3.1 on 2020-09-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userpp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpp',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
