# Generated by Django 3.1 on 2020-09-11 11:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200911_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='post',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='post_part_1',
            field=models.CharField(blank=True, default=None, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='post_part_2',
            field=models.CharField(blank=True, default=None, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='subtitle',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 11, 11, 52, 36, 599635, tzinfo=utc)),
        ),
    ]
