# Generated by Django 3.1 on 2020-09-12 19:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200912_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='city',
            new_name='place',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 12, 19, 3, 14, 978619, tzinfo=utc)),
        ),
    ]
