# Generated by Django 3.1 on 2020-08-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0003_auto_20200824_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='location_url',
            field=models.CharField(default=None, max_length=5000),
        ),
    ]
