# Generated by Django 3.1 on 2020-08-27 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0008_auto_20200827_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date',
        ),
    ]
