# Generated by Django 3.1 on 2020-08-27 12:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0009_remove_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 27, 12, 23, 55, 550080, tzinfo=utc)),
        ),
    ]
