# Generated by Django 3.1 on 2020-08-29 09:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0012_auto_20200828_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 29, 9, 42, 32, 628481, tzinfo=utc)),
        ),
    ]
