# Generated by Django 3.1 on 2020-08-29 10:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0013_auto_20200829_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 29, 10, 8, 1, 71992, tzinfo=utc)),
        ),
    ]
