# Generated by Django 3.1 on 2020-08-30 12:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0016_auto_20200830_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='avg_rating',
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 30, 12, 22, 59, 29166, tzinfo=utc)),
        ),
    ]
