# Generated by Django 3.1 on 2020-08-30 12:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0017_auto_20200830_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 30, 12, 46, 6, 668463, tzinfo=utc)),
        ),
    ]
