# Generated by Django 3.1 on 2020-08-31 08:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0019_auto_20200830_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 31, 8, 39, 14, 428221, tzinfo=utc)),
        ),
    ]
