# Generated by Django 3.1 on 2020-09-01 08:46

import accommodation.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0020_auto_20200831_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='check_out',
            field=models.DateField(default=accommodation.models.next_day),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 1, 8, 46, 51, 264062, tzinfo=utc)),
        ),
    ]
