# Generated by Django 3.1 on 2020-09-01 20:11

import accommodation.models
import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0021_auto_20200901_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='check_in',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_out',
            field=models.DateField(blank=True, default=accommodation.models.next_day, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 1, 20, 11, 27, 325109, tzinfo=utc)),
        ),
    ]
