# Generated by Django 3.1 on 2020-09-02 11:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0027_auto_20200902_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 2, 11, 31, 21, 129460, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='LikedHotel',
        ),
    ]
