# Generated by Django 3.1 on 2020-09-02 19:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0028_auto_20200902_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 2, 19, 23, 34, 967585, tzinfo=utc)),
        ),
    ]
