# Generated by Django 3.1 on 2020-09-03 11:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0030_auto_20200903_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 3, 11, 31, 22, 731972, tzinfo=utc)),
        ),
    ]
