# Generated by Django 3.1 on 2020-09-09 14:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0031_auto_20200903_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='geo_latitude',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='geo_longitude',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_website',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='maps_url',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='number_of_stars',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='hotel',
            name='telephone',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='type',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 9, 14, 18, 8, 330699, tzinfo=utc)),
        ),
    ]
