# Generated by Django 3.1 on 2020-09-14 08:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0041_auto_20200912_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='geo_latitude',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='geo_longitude',
        ),
        migrations.AddField(
            model_name='hotel',
            name='standard_price',
            field=models.IntegerField(blank=True, default=1000, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 14, 8, 53, 17, 787910, tzinfo=utc)),
        ),
    ]
